@baseUrl = http://127.0.0.1:8000

### 正常系：シンプルな会話
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0001_test_継続"
}

### 会話が続いている場合(けど自分の返信で終わっている。期待値：返信待ち)
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0002_test_デート"
}

### シーパラのような固有名詞に対して、自分あてに質問が来た場合
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0003_test"
}

### 会話無し（初回メッセージ）
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0004_test"
}

### 既読スルー
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0005_test"
}

### 会話が止まっている
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0006_test"
}

### デート打診直前
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0007_test"
}

### 少しだけ会話が長い
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0008_test"
}

### 勤務地が新宿
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0009_test"
}