@baseUrl = http://127.0.0.1:8000

### 正常系：シンプルな会話
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0001"
}

### 会話が続いている場合(けど自分の返信で終わっている。期待値：返信待ち)
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0002"
}

### 会話が少ない場合
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0003"
}

### 会話無し（初回メッセージ）
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0004"
}

### 既読スルー
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0005"
}

### 会話が止まっている
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0006"
}

### デート打診直前
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0007"
}

### 少しだけ会話が長い
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0008"
}

### 勤務地が新宿
POST {{baseUrl}}/reply
Content-Type: application/json

{
  "id": "with_0009"
}